CREATE DATABASE hhplus;

USE hhplus;
hhpluslecture_history

DROP TABLE lecture;
CREATE TABLE LECTURE(
		LECTURE_ID INT NOT NULL AUTO_INCREMENT
	, 	LECTURE_NM CHAR(20) NOT NULL
	,	CAPACITY INT NOT NULL DEFAULT 30 
	,	ENROLL_START_DATE DATE NOT NULL 
	,	INSTRUCTOR CHAR(10) NOT NULL	
	
	,CONSTRAINT LECTURE_PK PRIMARY KEY(LECTURE_ID)
);

DROP TABLE student
CREATE TABLE STUDENT(
		STUDENT_ID INT NOT NULL AUTO_INCREMENT
	, 	STUDENT_NM CHAR(10) NOT NULL
	
	,CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID)
);

CREATE TABLE LECTURE_HISTORY(
		HISTORY_ID INT NOT NULL AUTO_INCREMENT
	, 	STUDENT_ID INT NOT NULL
	, 	LECTURE_ID INT NOT NULL
	,	REG_DATE DATETIME NOT NULL 

	,CONSTRAINT LECTURE_HISTORY_PK PRIMARY KEY(HISTORY_ID)
	
	CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LECTURE_ID FOREIGN KEY (LECTURE_ID) REFERENCES LECTURE(LECTURE_ID) ON DELETE CASCADE
);
